.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
    - |
      curl -Os https://uploader.codecov.io/v0.1.0_4653/linux/codecov

      chmod +x codecov
      ./codecov -t $CODECOV_TOKEN -r gwario/Just4Fun.jl
Julia 1.9:
  image: julia:1.9
  extends:
    - .script
    - .coverage