.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.instantiate()
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        pf = process_folder()
        
        # codecov.io
        Codecov.submit_local(pf)
        
        # simple print
        c, t = get_summary(pf)
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
Julia 1.9:
  image: julia:1.9
  extends:
    - .script
    - .coverage